include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  # errors:
  #   prefer_const_declarations: error
  #   prefer_const_constructors: error

linter:
  rules:
    - sort_constructors_first
    - prefer_single_quotes
