name: ble_test
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bluetooth_low_energy: ^4.0.0
  convert: ^3.1.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
